[versions]
androidGradlePlugin = "8.4.0"
androidx-junit = "1.1.5"
appcompat = "1.6.1"
barcode-scanning = "17.2.0"
camera-core = "1.2.3"
camera-extensions = "1.2.3"
camera-lifecycle = "1.2.3"
camera-view = "1.2.3"
constraintlayout = "2.1.4"
core-ktx = "1.13.1"
espresso-core = "3.5.1"
junit = "4.13.2"
kotlin = "1.9.23"
material = "1.12.0"

[libraries]
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
androidx-camera-camera2 = { module = "androidx.camera:camera-camera2", version.ref = "camera-core" }
androidx-camera-extensions = { module = "androidx.camera:camera-extensions", version.ref = "camera-extensions" }
androidx-camera-lifecycle = { module = "androidx.camera:camera-lifecycle", version.ref = "camera-lifecycle" }
androidx-camera-view = { module = "androidx.camera:camera-view", version.ref = "camera-view" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "core-ktx" }
androidx-espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espresso-core" }
androidx-junit = { module = "androidx.test.ext:junit", version.ref = "androidx-junit" }
google-barcode-scanning = { module = "com.google.mlkit:barcode-scanning", version.ref = "barcode-scanning" }
google-material = { module = "com.google.android.material:material", version.ref = "material" }
junit = { module = "junit:junit", version.ref = "junit" }

[plugins]
androidApplication = { id = "com.android.application", version.ref = "androidGradlePlugin" }
androidLibrary = { id = "com.android.library", version.ref = "androidGradlePlugin" }
kotlin = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }